"""Per-fabric dump of the geometry stress-test corpus.

Reproduces the same fabrics generated by the three randomized stress tests in
`test_fabric_geometry.py` (using the same fixed seeds) and writes a
human-readable report containing the mask, dimensions, and per-fabric
geometry metrics for each one.

The aggregate totals at the bottom of each section match the per-section
summary lines printed by the test suite exactly.

Usage:
    cd FABulous
    SETUPTOOLS_SCM_PRETEND_VERSION_FOR_FABULOUS_FPGA=0.0.0+local \\
        uv run --frozen python tests/geometry_generator_test/dump_random_fabrics.py

Writes `random_fabrics_dump.txt` next to this script (~440 KB, 1314 fabrics).
"""

import random
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))

from fabulous.geometry_generator.fabric_geometry import FabricGeometry
from test_fabric_geometry import (
    _random_rectangular_mask,
    _random_t_shape_mask,
    _stats_for,
    _thin_masks,
    make_fabric,
)


_BORDER_GLYPH = {
    "CORNER": "C",
    "NORTHSOUTH": "N",
    "EASTWEST": "W",
    "NONE": "o",
}


def render_classified_mask(mask: list[list[bool]], geometry: FabricGeometry) -> str:
    """Render the fabric with each tile shown as its border-class glyph.

    Legend: C = CORNER, N = NORTHSOUTH, W = EASTWEST, o = NONE (interior),
    . = NULL.
    """
    rendered_rows = []
    for r, row in enumerate(mask):
        chars = []
        for c, occupied in enumerate(row):
            if not occupied:
                chars.append(".")
                continue
            tg = geometry.tileGeomMap[f"T_{r}_{c}"]
            chars.append(_BORDER_GLYPH[tg.border.name])
        rendered_rows.append("".join(chars))
    return "\n        ".join(rendered_rows)


def border_breakdown(geometry: FabricGeometry) -> Counter:
    counts: Counter = Counter()
    for tg in geometry.tileGeomMap.values():
        counts[tg.border.name] += 1
    return counts


def dump_fabric(idx: int, mask: list[list[bool]], out) -> tuple[int, int, int]:
    geometry = FabricGeometry(make_fabric(mask))
    rows, cols = len(mask), len(mask[0])
    occupied = sum(sum(1 for c in row if c) for row in mask)
    border, fallback, wires = _stats_for(geometry)
    classes = border_breakdown(geometry)
    out.write(
        f"--- #{idx:04d}  {rows}x{cols}  occupied={occupied}  "
        f"border={border}  fallback={fallback}  wires={wires}\n"
    )
    out.write(f"    classes: {dict(classes)}\n")
    out.write(f"    mask:\n        {render_classified_mask(mask, geometry)}\n\n")
    return border, fallback, wires


def dump_section(out, title: str, fabrics) -> None:
    out.write("=" * 75 + "\n")
    out.write(f"{title}\n")
    out.write("=" * 75 + "\n\n")
    totals = [0, 0, 0]
    count = 0
    for idx, mask in enumerate(fabrics, start=1):
        b, f, w = dump_fabric(idx, mask, out)
        totals[0] += b
        totals[1] += f
        totals[2] += w
        count = idx
    out.write(
        f"{title.split()[0]} TOTAL: {count} fabrics | "
        f"border={totals[0]}  fallback={totals[1]}  wires={totals[2]}\n\n"
    )


def main(out_path: Path) -> None:
    with out_path.open("w") as out:
        out.write("# Per-fabric dump for the geometry stress harness\n")
        out.write("# Seeds: rectangular=0xFAB00010, T-shape=0xFAB00020\n")
        out.write(
            "# Format: dims, occupied tiles, border-tile count, "
            "fallback hits, wire-line count, border classification breakdown, mask\n"
        )
        out.write(
            "# Mask legend: C = CORNER, N = NORTHSOUTH, W = EASTWEST, "
            "o = NONE (interior), . = NULL\n\n"
        )

        rng = random.Random(0xFAB00010)
        dump_section(
            out,
            "RECTANGULAR (250 fabrics, seed 0xFAB00010)",
            (_random_rectangular_mask(rng) for _ in range(250)),
        )

        rng = random.Random(0xFAB00020)
        dump_section(
            out,
            "T-SHAPE (1000 fabrics, seed 0xFAB00020)",
            (_random_t_shape_mask(rng) for _ in range(1000)),
        )

        dump_section(
            out,
            "THIN 1xN and Nx1 (64 fabrics, deterministic)",
            _thin_masks(),
        )


if __name__ == "__main__":
    out = HERE / "random_fabrics_dump.txt"
    main(out)
    print(f"wrote {out}")
